name: .NET Core

on: [push]

env:
  BUILD_CONFIGURATION: Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Fetch Code History
      run: git fetch #--prune --unshallow

    - name: Setup NextVersion
      run: |
        NEXT_VERSION=$(git describe --always --abbrev=0 --tags)
        sed -i "s/^next-version:.*$/next-version: $NEXT_VERSION/" GitVersion.yml
        cat GitVersion.yml
        
    - name: Setup GitVersion (DOCKER)
      uses: docker://gittools/gitversion
      with:
        args: '-nocache -output buildserver'
        
    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.6.1
      with:
          versionSpec: '5.1.x'
    
    - name: Execute GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.6.1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.101'
        
    - name: Setup Nuget
      run: sed -i 's/GITHUB_TOKEN/${{ secrets.GITHUB_TOKEN }}/g' nuget.config
      working-directory: ./dummy

    - name: Build and Package
      run:  |
        versionPrefix="${{ steps.gitversion.outputs.majorMinorPatch }}"
        versionSuffix="${{ github.sha }}"
        dotnet build -c $BUILD_CONFIGURATION -p:VersionPrefix="${versionPrefix}" --version-suffix "v${versionSuffix:0:7}"
      working-directory: ./dummy

    - name: Push packages to GitHub 
      run: dotnet nuget push ./bin/$BUILD_CONFIGURATION/*.nupkg --source 'github'
      working-directory: ./dummy

